/*
 * JSP generated by Resin Professional 4.0.38 (built Tue, 17 Dec 2013 09:49:45 PST)
 */

package _jsp._web_22dinf._mall;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _cookie__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
	String path = request.getContextPath();

    out.write(_jsp_string1, 0, _jsp_string1.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1257324557874484737L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/mall/cookie.jsp"), -8018162495489181513L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${path}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;

  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  static {
    _jsp_string3 = "/js/jquery.cookie.js\"></script>\r\n<script type=\"text/javascript\">\r\n\r\n	var GetCookieValue = function(cookieName){\r\n		//js\u5b9e\u73b0\r\n		/* var cookieValue = document.cookie;\r\n		var cookieArray = cookieValue.split(\";\");\r\n		var resultCookieValue = null;\r\n		for(var i=0;i<cookieArray.length;i++){\r\n			if(cookieArray[i].indexOf(cookieName)!=-1){\r\n				resultCookieValue =cookieArray[i].split(\"=\")[1];\r\n				break;\r\n			}\r\n		}\r\n		return resultCookieValue; */\r\n		//jquery.cookie\r\n		var cookieValue = $.cookie(cookieName);\r\n		return cookieValue;\r\n		\r\n	}\r\n\r\n	var SetCookieValue = function(cookieName,cookieValue,expire){\r\n		\r\n		var expDate = new Date();\r\n		expDate.setTime(expDate.getTime()+expire);\r\n		var expString = ((expire==\"-1\") ? \"\" : (\";expires=\"+expDate.toGMTString()));\r\n		//js\u5b9e\u73b0\r\n		//document.cookie=cookieName+\"=\"+cookieValue+expString;\r\n		//jquery.cookie\r\n		$.cookie(cookieName,cookieValue,{expires:expire});\r\n		\r\n		\r\n	}\r\n	var getDocumentCookie = function(){\r\n		//alert(GetCookieValue(\"firstcookie\"));\r\n		//var cookieValue = GetCookieValue(\"firstcookie\");\r\n		document.getElementById(\"spanId\").innerHTML=GetCookieValue(\"firstcookie\");\r\n		\r\n	}\r\n	$(function(){\r\n		$(\"#spanId\").text(GetCookieValue(\"firstcookie\"));\r\n		SetCookieValue(\"secondcookie\",\"secondValue\",30*60);\r\n	});\r\n</script>\r\n</head>\r\n<body><!-- onload=\"getDocumentCookie();\" -->\r\n	<a id=\"dd\" href=\"".toCharArray();
    _jsp_string4 = "/cookie/getCookie.action\" >\u53d1\u9001cookie</a>\r\n	<span id=\"spanId\"></span>\r\n</body>\r\n</html>\r\n\r\n".toCharArray();
    _jsp_string2 = "/js/jquery-1.7.2.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string1 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" >\r\n<head>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string0 = "\r\n".toCharArray();
  }
}
